#!/usr/bin/env python3
"""Design tokens for a delivery target: frame size, safe insets, type scale, strokes.

Every number that decides whether text survives a phone feed lives here, derived
once from the target's width and height, and emitted as JSON or as a TypeScript
module the scenes import. Also computes WCAG contrast for two colours.

Usage:
    python3 frame_tokens.py --target linkedin-4x5                 # JSON
    python3 frame_tokens.py --target linkedin-4x5 --target pptx-16x9 --ts > src/tokens.ts
    python3 frame_tokens.py --target custom --width 1440 --height 1440 [--feed]
    python3 frame_tokens.py contrast "#F5F7FF" "#0B1020"
    python3 frame_tokens.py --self-test

Exit codes: 0 = ok, 1 = bad arguments or a contrast check that fails. Stdlib only.
"""

from __future__ import annotations

import argparse
import json
import math
import sys

# Target id -> (width, height, safe-zone family). Delivery encoding lives in
# animation-export-presets/presets.json; these are the DESIGN sizes. Keep the two
# tables in step when adding a target. fps comes from the storyboard, never from here.
TARGETS: dict[str, tuple[int, int, str]] = {
    "linkedin-4x5": (1080, 1350, "feed"),
    "linkedin-1x1": (1080, 1080, "feed"),
    "linkedin-9x16": (1080, 1920, "vertical"),
    "linkedin-16x9": (1920, 1080, "feed"),
    "pptx-16x9": (1920, 1080, "slide"),
    "pptx-4k": (1920, 1080, "slide"),  # designed at 1080p, rendered with --scale 2
    "gif-loop": (1080, 1080, "feed"),  # designed square, downscaled to <= 800 px on export
}
# The narrowest display the tokens are designed for: a phone feed showing the video
# at 390 logical px wide. Feed and vertical targets scale with WIDTH (what the phone
# shows), slides scale with HEIGHT (the projector fills the height).
PHONE_WIDTH = 390
MIN_DIM, MAX_DIM = 240, 8192
# Safe insets as fractions of height (top/bottom) and width (left/right).
# feed: EBU R95 graphics-safe 5% per edge plus a 12% bottom band for platform
# controls (LinkedIn says "keep the edges free", gives no number: heuristic).
# vertical: Meta Reels guidance 14% top / 35% bottom / 6% sides, rounded up so the
# essentials also sit inside the central 4:5 crop some feeds apply.
# slide: EBU R95 graphics-safe 5%.
SAFE: dict[str, tuple[float, float, float, float]] = {
    "feed": (0.05, 0.05, 0.12, 0.05),
    "vertical": (0.15, 0.06, 0.35, 0.06),
    "slide": (0.05, 0.05, 0.05, 0.05),
}
# Type scale at a 1080 px design width. Derivation (references/legibility.md): a
# 1080-wide video shows at ~390 logical px on a phone, so 1 logical px ~ 2.77 video
# px; Apple's 11 pt (logical px) minimum -> 32 px, 17 pt body -> 48 px.
BASE_TYPE = {"caption": 32, "body": 48, "headline": 84, "display": 120}
BASE_STROKE = {"min": 3, "regular": 4, "bold": 8}
MIN_WEIGHT = {"caption": 500, "body": 500, "headline": 600, "display": 700}
COLUMNS = 12


def tokens_for(target: str, width: int, height: int, family: str) -> dict:
    if not (MIN_DIM <= width <= MAX_DIM and MIN_DIM <= height <= MAX_DIM):
        raise ValueError(f"width/height must be within {MIN_DIM}..{MAX_DIM}")
    s = (height if family == "slide" else width) / 1080
    top, right, bottom, left = SAFE[family]
    if family == "vertical":
        # Some feeds crop tall video to a centred 4:5; keep essentials inside it.
        crop = max(0.0, (height - 1.25 * width) / 2) / height
        top, bottom = max(top, crop), max(bottom, crop)
    safe = {
        "top": round(height * top),
        "right": round(width * right),
        "bottom": round(height * bottom),
        "left": round(width * left),
    }
    safe_w = width - safe["left"] - safe["right"]
    safe_h = height - safe["top"] - safe["bottom"]
    gutter = round(width * 0.02)
    column = (safe_w - gutter * (COLUMNS - 1)) / COLUMNS
    type_px = {k: math.ceil(v * s - 1e-9) for k, v in BASE_TYPE.items()}  # minimums round up
    return {
        "target": target,
        "width": width,
        "height": height,
        "scale": round(s, 4),
        "phonePreviewScale": round(PHONE_WIDTH / width, 4),
        "safe": safe,
        "safeWidth": safe_w,
        "safeHeight": safe_h,
        "grid": {"columns": COLUMNS, "gutter": gutter, "column": round(column, 2)},
        "type": type_px,
        "minWeight": MIN_WEIGHT,
        "lineHeight": 1.15,
        "maxCharsPerLine": max(12, int(safe_w / (type_px["headline"] * 0.55))),
        "stroke": {k: math.ceil(v * s - 1e-9) for k, v in BASE_STROKE.items()},
        "icon": {
            "sm": round(type_px["body"] * 1.25),
            "md": type_px["headline"],
            "lg": round(type_px["display"] * 1.5),
        },
        "radius": round(16 * s),
    }


def to_ts(all_tokens: list[dict]) -> str:
    body = json.dumps({t["target"]: t for t in all_tokens}, indent=2)
    return (
        "// Generated by vector-scene-layout/scripts/frame_tokens.py. Do not edit by hand;\n"
        "// re-run the script when a target changes.\n"
        f"export const tokensByTarget = {body} as const;\n\n"
        "export type TargetId = keyof typeof tokensByTarget;\n"
        "export type Tokens = (typeof tokensByTarget)[TargetId];\n"
        "export const tokensFor = (target: string): Tokens => {\n"
        "  const t = tokensByTarget[target as TargetId];\n"
        "  if (!t) throw new Error(`unknown target ${target}`);\n"
        "  return t;\n"
        "};\n"
    )


def srgb_to_linear(c: float) -> float:
    c /= 255
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def luminance(hex_colour: str) -> float:
    h = hex_colour.lstrip("#")
    if len(h) == 3:
        h = "".join(ch * 2 for ch in h)
    if len(h) != 6:
        raise ValueError(f"not a hex colour: {hex_colour}")
    r, g, b = (int(h[i : i + 2], 16) for i in (0, 2, 4))
    return 0.2126 * srgb_to_linear(r) + 0.7152 * srgb_to_linear(g) + 0.0722 * srgb_to_linear(b)


def contrast(fg: str, bg: str) -> float:
    a, b = luminance(fg), luminance(bg)
    hi, lo = max(a, b), min(a, b)
    return (hi + 0.05) / (lo + 0.05)


def self_test() -> None:
    t = tokens_for("linkedin-4x5", *TARGETS["linkedin-4x5"])
    assert t["safe"] == {"top": 68, "right": 54, "bottom": 162, "left": 54}, t["safe"]
    assert t["type"] == {"caption": 32, "body": 48, "headline": 84, "display": 120}, t["type"]
    assert t["stroke"]["min"] == 3 and t["phonePreviewScale"] == 0.3611
    wide = tokens_for("linkedin-16x9", *TARGETS["linkedin-16x9"])
    assert wide["type"]["body"] == 86 and wide["scale"] == 1.7778, wide  # feed scales with width
    slide = tokens_for("pptx-16x9", *TARGETS["pptx-16x9"])
    assert slide["type"]["body"] == 48, slide  # slides scale with height
    v = tokens_for("linkedin-9x16", *TARGETS["linkedin-9x16"])
    assert v["safe"]["bottom"] == 672 and v["safe"]["top"] == 288, v["safe"]
    tall = tokens_for("custom", 1080, 2400, "vertical")
    assert tall["safe"]["top"] == 525 and tall["safe"]["bottom"] == 840, tall[
        "safe"
    ]  # 4:5 crop containment
    big = tokens_for("custom", 2160, 2160, "slide")
    assert big["type"]["body"] == 96 and big["scale"] == 2.0
    tiny = tokens_for("custom", 250, 250, "feed")
    assert tiny["type"]["caption"] == 8, tiny[
        "type"
    ]  # ceil(32 * 250/1080 = 7.4) keeps the 11 pt floor
    try:
        tokens_for("custom", 2, 2, "slide")
    except ValueError:
        pass
    else:
        raise AssertionError("tiny dimensions must be rejected")
    assert abs(contrast("#FFFFFF", "#000000") - 21.0) < 1e-6
    assert contrast("#7A7A7A", "#F2F2F2") < 4.5
    assert contrast("#F5F7FF", "#0B1020") > 4.5
    ts = to_ts([t, v])
    assert '"linkedin-9x16"' in ts and "tokensFor" in ts
    print("self-test OK")


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    sub = ap.add_subparsers(dest="cmd")
    c = sub.add_parser("contrast", help="WCAG contrast ratio of two hex colours")
    c.add_argument("fg")
    c.add_argument("bg")
    c.add_argument("--large", action="store_true", help="apply the 3:1 large-text threshold")
    ap.add_argument(
        "--target",
        action="append",
        default=[],
        help="preset id, repeatable; 'custom' needs --width/--height",
    )
    ap.add_argument("--width", type=int)
    ap.add_argument("--height", type=int)
    ap.add_argument(
        "--feed",
        action="store_true",
        help="custom target is for a phone feed (scale with width) rather than a slide",
    )
    ap.add_argument("--ts", action="store_true", help="emit a TypeScript module instead of JSON")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()
    if args.self_test:
        self_test()
        return 0
    if args.cmd == "contrast":
        try:
            ratio = contrast(args.fg, args.bg)
        except ValueError as exc:
            print(f"ERROR {exc}", file=sys.stderr)
            return 1
        needed = 3.0 if args.large else 4.5
        ok = ratio >= needed
        print(
            f"{ratio:.2f}:1 {'PASS' if ok else 'FAIL'} (needs {needed}:1 for {'large' if args.large else 'body'} text)"
        )
        return 0 if ok else 1
    if not args.target:
        ap.error("--target required (or the contrast subcommand)")
    out = []
    for target in args.target:
        if target == "custom":
            if not (args.width and args.height):
                ap.error("custom target needs --width and --height")
            if args.width % 2 or args.height % 2:
                ap.error("width and height must be even (H.264 4:2:0)")
            family = (
                "vertical" if args.height > args.width * 1.5 else ("feed" if args.feed else "slide")
            )
            try:
                out.append(tokens_for("custom", args.width, args.height, family))
            except ValueError as exc:
                ap.error(str(exc))
        elif target in TARGETS:
            w, h, family = TARGETS[target]
            out.append(tokens_for(target, w, h, family))
        else:
            ap.error(f"unknown target {target!r}; known: {', '.join(TARGETS)} or custom")
    print(to_ts(out) if args.ts else json.dumps(out if len(out) > 1 else out[0], indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
